# Change these first
owner: haliliceylan # Your GitHub organization or username
repo: uptime-haliliceylan # Your GitHub repository name

# Add your sites here
sites:
  - name: Abatır
    url: https://abatir.$MAIN_DOMAIN
  - name: Abamotors
    url: https://abamotors.$MAIN_DOMAIN
  - name: Betmaster
    url: https://betmaster.$MAIN_DOMAIN
  - name: diyetisyen
    url: $DIYETISYEN_DOMAIN
  - name: Minio
    url: https://minio.$MAIN_DOMAIN
  - name: func
    url: https://func.$MAIN_DOMAIN
  - name: portainer
    url: https://portainer.$MAIN_DOMAIN
 
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime-haliliceylan
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Halil
  introTitle: "Hey"
  introMessage: Hey
  navbar:
    - title: Status
      href: /uptime-haliliceylan
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
